# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facerecognizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
import recognizer as rg
import cv2

app = QtWidgets.QApplication(sys.argv)

class FaceRecognizerDlg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("m_dlgStart")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.m_lbCameraView = QtWidgets.QLabel(Dialog)
        self.m_lbCameraView.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.m_lbCameraView.setFont(font)
        self.m_lbCameraView.setAlignment(QtCore.Qt.AlignCenter)
        self.m_lbCameraView.setObjectName("m_lbCameraView")
        self.verticalLayout_3.addWidget(self.m_lbCameraView)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.m_btnFileOpen = QtWidgets.QPushButton(Dialog)
        self.m_btnFileOpen.setMinimumSize(QtCore.QSize(120, 40))
        self.m_btnFileOpen.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.m_btnFileOpen.setFont(font)
        self.m_btnFileOpen.setObjectName("m_btnFileOpen")
        self.horizontalLayout_2.addWidget(self.m_btnFileOpen)
        self.m_btnCameraStart = QtWidgets.QPushButton(Dialog)
        self.m_btnCameraStart.setMinimumSize(QtCore.QSize(120, 40))
        self.m_btnCameraStart.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.m_btnCameraStart.setFont(font)
        self.m_btnCameraStart.setObjectName("m_btnCameraStart")
        self.horizontalLayout_2.addWidget(self.m_btnCameraStart)
        self.m_btnFaceVerify = QtWidgets.QPushButton(Dialog)
        self.m_btnFaceVerify.setMinimumSize(QtCore.QSize(120, 40))
        self.m_btnFaceVerify.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.m_btnFaceVerify.setFont(font)
        self.m_btnFaceVerify.setObjectName("m_btnFaceVerify")
        self.horizontalLayout_2.addWidget(self.m_btnFaceVerify)
        self.m_btnExit = QtWidgets.QPushButton(Dialog)
        self.m_btnExit.setMinimumSize(QtCore.QSize(120, 40))
        self.m_btnExit.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.m_btnExit.setFont(font)
        self.m_btnExit.setObjectName("m_btnExit")
        self.horizontalLayout_2.addWidget(self.m_btnExit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.m_lvResult = QtWidgets.QListView(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.m_lvResult.setFont(font)
        self.m_lvResult.setObjectName("m_lvResult")
        self.verticalLayout_2.addWidget(self.m_lvResult)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.m_btnFileOpen.clicked.connect(self.onSelectDirectory)
        self.m_btnCameraStart.clicked.connect(self.onCameraStart)
        self.m_btnFaceVerify.clicked.connect(self.onFaceVerify)
        self.m_btnExit.clicked.connect(self.onExit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Face Recognizer"))
        self.m_lbCameraView.setText(_translate("Dialog", "Please select database directory and press start button"))
        self.m_btnFileOpen.setText(_translate("Dialog", "Select"))
        self.m_btnCameraStart.setText(_translate("Dialog", "Camera Open"))
        self.m_btnFaceVerify.setText(_translate("Dialog", "Verify"))
        self.m_btnExit.setText(_translate("Dialog", "Exit"))

        self.file = None

    def onSelectDirectory(self):
        options = QFileDialog.Options()
        self.file, _ = QFileDialog.getOpenFileName(None, "Select File", "", "All Files (*);;Database Files (*.jpg)", options=options)
        
        # Display the selected file path
        if self.file:
            QMessageBox.information(None, "Database", f"Selected File: {self.file}")

        else:
            QMessageBox.warning(None, "Database", "Please select directory")

    def onCameraStart(self):
        # Replace with your actual IP camera stream URL
        ip_camera_url = "http://<username>:<password>@<ip_address>:<port>/video"
        rg.openCamera(self, ip_camera_url)
    
    def onFaceVerify(self):
        rg.verify_face(self, self.file)
        return

    def onExit(self):
        sys.exit(app.exec_())

if __name__ == "__main__":
    Dialog = QtWidgets.QDialog()
    ui = FaceRecognizerDlg()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
